### ISSUE TITLE
Consistent naming

### ISSUE THREAD

**Issue by Maikon** [sohbaker/contact-manager#7]
Any reason why these are named differently in this case (`f_name`, `s_name`)? 🙂

https://github.com/sohbaker/contact-manager/blob/0b30fe240792d4972f7bf82710e92323af507b6b/lib/person.rb#L4-L6

**Comment by sohbaker** [comment]
I've removed lines 11 - 23 (they were no longer doing anything). 
The initialize method is still the same.... The Person class is accessed from the ManagePhonebook class, so needed to define what the arguments correspond to, so that it could then create the hash.

**Comment by sohbaker** [comment]
names are now consistent.
